import { useState } from 'react';
import { AlertTriangle, CheckCircle2, CircleAlert, Map, Satellite, WifiOff } from 'lucide-react';

const statusIcons = { normal: CheckCircle2, warning: AlertTriangle, critical: CircleAlert, offline: WifiOff };

export default function RegionalMap({ locations }) {
  const [mode, setMode] = useState('2D');
  const [selected, setSelected] = useState(null);

  return <div className="regional-map"><div className="dlh-card-header"><div><p className="eyebrow">REGIONAL GIS MAP</p><h2 id="map-title">Pekalongan</h2></div><div className="dlh-toggle" role="group" aria-label="Map view"><button type="button" className={mode === '2D' ? 'active' : ''} onClick={() => setMode('2D')}><Map size={15} aria-hidden="true" />2D</button><button type="button" className={mode === 'Satellite' ? 'active' : ''} onClick={() => setMode('Satellite')}><Satellite size={15} aria-hidden="true" />Satellite</button></div></div><div className={`dlh-map-visual dlh-map-${mode.toLowerCase()}`} role="group" aria-label={`Pekalongan station map in ${mode} view`}><span className="dlh-map-label dlh-map-label-north">NORTH COASTAL</span><span className="dlh-map-label dlh-map-label-city">PEKALONGAN</span>{locations.map((location) => { const Icon = statusIcons[location.status] || CircleAlert; return <button key={location.id} type="button" className={`dlh-map-marker dlh-marker-${location.status}`} style={{ left: `${location.x}%`, top: `${location.y}%` }} title={`${location.name} — ${location.status}`} aria-label={`${location.name}, ${location.type === 'industry' ? 'industry' : 'monitoring point'}, status ${location.status}, ${location.parameter} ${location.reading}`} onClick={() => setSelected(location)}><Icon size={13} aria-hidden="true" /></button>; })}{selected && <div className="dlh-map-popover" role="status"><strong>{selected.name}</strong><span>{selected.type === 'industry' ? 'Industry' : 'Monitoring point'}</span><span>Status: {selected.status}</span><span>{selected.parameter}: {selected.reading}</span><button type="button" onClick={() => setSelected(null)}>Close</button></div>}<div className="dlh-map-scale">2 km</div></div><div className="dlh-map-legend"><span><i className="dlh-legend-dot dlh-marker-normal" />Industry · Normal</span><span><i className="dlh-legend-dot dlh-marker-warning" />Monitoring · Waspada</span><span><i className="dlh-legend-dot dlh-marker-critical" />Critical incident</span><span><i className="dlh-legend-dot dlh-marker-offline" />Offline station</span></div></div>;
}
